
    <footer class="text-white bg-primary" id="footer">
      <div class="container">
       <div class="row">
       
      
       <div class="col-lg-4 col-md-12">
		       <h4 class="yellow">About ASURE</h4>		    
					<p>The ASURE Accommodation Group consists of quality accommodation properties throughout New Zealand.</p>
					<a class="btn btn-primary border" href="ASURE.html" title="About ASURE Accommodation">About ASURE</a>
       </div>
       
       <div class="col-lg-5 col-md-12 my-3 my-lg-0">
	        <div class="loyaltyCard">
			      <a href="https://www.asurestay.com/assets/cards/7c57955257/Asure-Loyalty-Card-2020.pdf" target="_blank"><img alt="ASURE Nationwide Loyalty Programme" src="https://www.asurestay.com/~images/template/common/ASURE_loyaltycard-01.png"></a>
		      </div>
		      <div class="loyaltyInner">
	          <h4>ASURE Loyalty Programme</h4>
						<p>Stay at three or more ASURE Accommodation Group properties and receive $100 credit off your 10th stay!</p>
						<a class="btn btn-primary border" href="https://www.asurestay.com/properties/search.html" title="Book Your ASURE Stay Online">Book Now</a>
					</div>
       </div>
       
       <div class="col-lg-3 col-md-12 text-lg-right text-center">
         <a target="_blank" href="https://play.google.com/store/apps/details?id=com.guestfolder.asure"><img class="mb-2" src="images/google-play-store.png" alt="Download ASURE App from Google Play Store" /></a>
         <a target="_blank" href="https://apps.apple.com/us/app/asure-accommodation-group/id1150322731?ls=1"><img class="mb-2" src="images/app-store.png" alt="Download ASURE App from App Store" /></a>
       </div>
       
      		<div class="col-lg-12 mx-auto text-center mt-4 p-lg-0">
            <div class="footerCards">
							<img class="img-fluid" alt="Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards" src="https://www.asurestay.com/~images/template/common/ASURE_cards06.jpg" />
							<p class="px-3">ASURE Accommodation Group Accepts All Major Credit Cards and: Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards.</p>
						</div>
         </div>
         
        <div class="col-12 text-center">
	        <p class="lead">
						ASURE Accommodation Group <span class="dash">|</span>
						<a class="yellow" href="https://www.ASUREstay.com" title="ASURE Accommodation Group NZ" target="_blank">www.ASUREstay.com</a> <span class="dash">|</span>
						Your Comfort is ASUREd
					</p>
        </div>

       </div>
      </div>

    </footer>
    
    <div class="mx-auto w-100">
	      <div class="mx-auto col text-center" id="footerCopy">
				&copy; %YEAR% ASURE Accommodation Group - 
				<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
				<a href="https://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
				%CREDITLINK%
			  </div>
		  </div>
    
    <!-- Bootstrap core JavaScript -->  
    <script src="js/bootstrap.bundle.min.js"></script>

    <!-- Plugin JavaScript -->  
    <script src="js/jquery.easing.min.js"></script>

    <!-- Custom scripts for this template -->
    <script src="js/scrollreveal.min.js"></script>
    <script src="js/lightbox.min.js"></script>   
    <script src="js/custom.js"></script>    
    <script src="js/js.js"></script>

</body>