    
    <!-- Bootstrap/Plugin CSS -->
    <link href="css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom fonts for this template -->

    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,600,700&display=swap" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="css/custom.css" rel="stylesheet">
    <link href="css/datepicker.css" rel="stylesheet">
    <link href="css/lightbox.css" rel="stylesheet">
    
    <!-- favicon -->
		<link rel="shortcut icon" type="image/x-icon" href="images/favicon.png" />
		
		<script type="text/javascript" charset="utf-8" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkSeSSBYyppgXf_h-HF63jMsSMt9JI9q8&amp;sensor=false"></script>
		%WEBROOMS_JS_INCLUDE%
		
		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		
		/* color 1 */
		
		</style>
		
		<!--[if lte IE 8]>
			<link rel="stylesheet" type="text/css" href="css/ie.css" />
		<![endif]-->

    %SITE_CUSTOM_CONTENT_1%
    
</head>

<body id="page-top">
   <!-- Header -->
    <div class="bg-primary template-header">
      <div class="container-fluid">
        <div class="row align-items-center">
	        <div class="col-md-9 text-white d-inline-flex logo-tab">
	          <div>
	        	  <a class="navbar-brand js-scroll-trigger" href="#page-top"><img class="logo" src="images/logo_asure.png" alt="ASURE %SUBCATEGORY_NAME% Accommodation New Zealand"></a>
	        	</div>
	        	<div>
	        	  <h3>ASURE %SUBCATEGORY_NAME% Accommodation</h3>
							<span class="lead yellow">Your Comfort is ASUREd</span>
							<p>Book Your %SUBCATEGORY_NAME% Accommodation Online<br />
						   %SUBCATEGORY_NAME% Motels, Apartments, Motor Inns, &amp; Motor Lodges</p> 
						   <a class="d-block d-md-none btn btn-primary border mt-2" href="https://asure.web-rooms.com">Guest Login</a>
						</div>
	        </div>
	        
	        <div class="col-md-3 text-right d-none d-md-block">         	
					  <div><img src="images/logo_nzmade.png" alt="New Zealand Made" /></div>
					  <a class="btn btn-primary border mt-2" href="https://asure.web-rooms.com">Guest Login</a>
	        </div>
        </div>
      </div>
    </div>
