.slideshowRow { max-width:none; }
#slideshow { margin:0; }
#slideshow .slideshowGallery,
#slideshow .slideshowGallery ul,
#slideshow .slideshowGallery li,
#slideshow .slideshowGallery li .gallery-image { width:100%; height:500px; }
#bookingBox { left:0; right:0; bottom:50px; margin:auto; display:none; }
#slideshow .propPrev, 
#slideshow .propNext { z-index:999; font-weight:300; top:210px; opacity:0.3; left:20px; }
#slideshow .propNext { left:initial; right:20px; }

@media only screen and (max-width: 960px) 
{

#slideshow .slideshowGallery,
#slideshow .slideshowGallery ul,
#slideshow .slideshowGallery li,
#slideshow .slideshowGallery li .gallery-image { width:100%; height:300px; }

}