<!-- Footer -->
    <footer class="footer text-center bg-faded py-5">
      <div class="container">       
          <div class="col-md-12">
				        <img class="footer-logo" src="%SITE_CUSTOM_CONTENT_1%assets/Footer-Badges/212be229da/LAM-Logo.png" title="Look After Me" alt="Look After Me">
	        	<div class="copyright py-4 text-center">
				        <p>&copy; %YEAR% -	<a href="https://www.staydunedin.com/admin">Admin Login</a> - <a href="%SITE_CUSTOM_CONTENT_1%terms/" title="Terms and conditions ">Terms and conditions</a> - <a target="_blank" href="https://www.guesttraction.com/">Website by GuestTraction</a></p>
				    </div>
         </div>
      </div>
    </footer>