						
<div class="nav2 remove">
  %UL_NAV_1L%
</div>
		
<div id="pageFooter">
	<div class="row">
		<a href="index.html" title="Motel Association of New Zealand" class="manzLogo">
			Motel Association of New Zealand
		</a>
    <h2 class="siteTitle">%SITE_NAME%</h2>
  </div>
</div>

<div class="footerCopy">	
	&copy; %YEAR% Napier Motel Association. <a href="sitemap.html">Site Map</a> |	<a href="http://www.welman.co.nz/webrooms-login.asp">Admin Login</a>	
</div>


<script>
  var nav = responsiveNav(".nav-collapse");
</script>

