		
		<script src="js/jquery.cycle2.min.js"></script>
		<script src="js/jquery.cycle2.carousel.min.js"></script>
		<script src="js/jquery.cycle2.swipe.min.js"></script>		
		<script src="js/jquery.dotdotdot.min.js"></script>
		<script src="js/lightbox.min.js"></script>		
		<link href="css/lightbox.css" rel="stylesheet" />		
		
		<script src="js/moment.js" type="text/javascript"></script>
		<script src="js/jquery.daterangepicker.js" type="text/javascript"></script>
				
		<script src="js/js.js"></script>
		<script src="js/groupSearch.js"></script>
		<script src="%GLOBAL_ROOT%js/groupSearch_core.js"></script>
		
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&libraries=places,geometry"></script>		
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800" rel="stylesheet" type="text/css"/>
		
		<link rel="stylesheet" href="css/search.css" type="text/css"/>
		<link rel="stylesheet" href="css/daterangepicker.css" type="text/css"/>
		<link rel="icon" type="image/png" href="images/favicon.png" />
		
		<!-- Bootstrap -->
		<link rel="stylesheet" href="css/custom.css" type="text/css">
		<link href="css/bootstrap.min.css" rel="stylesheet">
		<script src="js/bootstrap.bundle.min.js"></script>
		<script src="js/scrollreveal.js"></script>
		<script src="js/creative.js"></script>
		<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">
		
		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		</style>
		
		%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
		
	</head>
	<body class="bodyStyle">
		
	<nav class="navbar navbar-expand-lg fixed-top text-uppercase" id="mainNav">
      <div class="container p-lg-0">
        
           
             
        <a href="https://www.stayrotorua.com"><img class="logo" src="%SITE_CUSTOM_CONTENT_1%assets/Uploads/8c181d7747/Rotorua-Motels-logo__ScaleHeightWzgwXQ.png" title="Rotorua Motels logo" alt="Rotorua Motels logo"></a>
          	 
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" 
        data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars" aria-hidden="true"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            
					<li class="current nav-item"><a class="nav-link menu-list" href="%SITE_CUSTOM_CONTENT_1%" title="Home">Home</a></li>
					<li class="link nav-item"><a class="nav-link menu-list" href="search.html" title="Search">Search</a></li>
					<li class="link nav-item"><a class="nav-link menu-list" href="%SITE_CUSTOM_CONTENT_1%about-ram/" title="About the Rotorua Association of Motels">About RAM</a></li>
          <li class="link nav-item"><a class="nav-link menu-list" href="%SITE_CUSTOM_CONTENT_1%contact-us/" title="Contact Us">Contact Us</a></li>
				  			  
          </ul>
        </div>
      </div>
    </nav>
						