

	 <section class="bg-light" id="removeFooter">
    
      <div class="container">
        <div class="row">
          <div class="col-lg-12 mx-auto text-center">
             <span>Stay Rotorua is powered by</span>
             <br>
		          <img class="logo" src="%SITE_CUSTOM_CONTENT_1%assets/Uploads/8c181d7747/Rotorua-Motels-logo__ScaleHeightWzEyMF0.png" title="Rotorua Motels logo" alt="Rotorua Motels logo">
		         <div>
		         	<a class="btn btn-dark mb-2" href="https://intranet.stayrotorua.com">RAM INTRANET LOGIN</a>
		         	<br>
		         	<a class="btn btn-dark" href="https://secure.web-rooms.co.nz/Login.asp">RAM PROPERTY PROFILE LOGIN</a>
		         </div>
          </div>

        </div>
      </div>
    
  </section>
	<div class="bg-dark text-light">	
			&copy; %YEAR% R.A.M. %CREDITLINK%
  </div>
		
	
