				
		<script src="js/moment.js" type="text/javascript"></script>
		<script src="js/jquery.daterangepicker.js" type="text/javascript"></script>
				
		<script src="js/js.js"></script>
		<script src="js/groupSearch.js"></script>
		<script src="https://secure.web-rooms.co.nz/js/groupSearch_core.js"></script>
		<script src="https://secure.web-rooms.co.nz/js/jquery.cookie.js"></script>
		
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkSeSSBYyppgXf_h-HF63jMsSMt9JI9q8&libraries=places,geometry"></script>		
		<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet" type="text/css"/>
		<link href='https://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet' type='text/css'>
		
		<link rel="stylesheet" href="css/search.css" type="text/css"/>
		<link rel="stylesheet" href="css/daterangepicker.css" type="text/css"/>
		<link rel="stylesheet" href="css/widget.css" type="text/css"/>		
		<link rel="icon" type="image/ico" href="images/favicon.ico" />
		
		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		</style>
		
		%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
		
	</head>
	<body class="bodyStyle">
		
						