<div class="footerBlock">
	<div class="row">
		<div class="footerASURE">
			<a href="index.html" title="ASUREstay.com - ASURE Accommodation Group New Zealand">
				<img src="images/logo_asure-home.png" alt="ASURE" />
			</a>
		</div>
		<div class="footerLogos">
			<hr />
			<a target="_blank" href="https://www.facebook.com/AsureAccommodation">
				<img src="images/logo_facebook.jpg" alt="ASURE Accommodation Group on Facebook" /></a>
			<a href="mobile.html">
				<img src="images/footer_app.jpg" alt="ASURE Accommodation Mobile App" /></a>	
			<a href="mailing-list.html">
				<img src="images/logo_mailchimp.jpg" alt="Sign Up To Our Mailing List" /></a>
		</div>
		<div class="footerNav">
			<hr />
			<ul>
				<li class="call-now">BOOK ONLINE OR FREE PHONE 0800 278 739, or +64 9 320 5913 (from outside New Zealand)</li>
			</ul>
			<hr />
			<ul>
				<li><a href="contact.html" title="Contact">Become an ASURE Member Property</a></li>
			</ul>
		</div>
		<div class="footerNav">
			<hr />
			<ul>
				<li><a href="index.html" title="Home">Home</a></li>
				<li><a href="about.html" title="About">About</a></li>
				<li><a href="members.html" title="Members">Members</a></li>
				<li><a href="search.html" title="Search">Search</a></li>
				<li><a href="promotions.html" title="Promos">Promos</a></li>
				<li><a href="vouchers.html" title="Vouchers">Vouchers</a></li>
				<li><a href="mobile.html" title="Mobile App">Mobile App</a></li>
				<li><a href="contact.html" title="Contact">Contact</a></li>
			</ul>
		</div>
		<div class="footerCards">
			<hr />
			<p>ASURE Accommodation Group Accepts All Major Credit Cards and: Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards.</p>
			<img src="images/ASURE_cards06.jpg" alt="Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards" />
		</div>
		<div class="footerCopy">
			<hr />
			&copy; %YEAR% ASURE Accommodation Group New Zealand - 
			<a href="sitemap.html" title="Sitemap">Sitemap</a> - 
			%CREDITLINK%
		</div>
	</div>
</div>

<script src="js/jquery-scrolltofixed-min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.headerBar').scrollToFixed();
    });
</script>