  <section class="text-white pb-0" id="contact-footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto text-center">
            <img class="logo mb-3" src="images/logo_asure-home.png" alt="Discover New Zealand" />
            <div class="mb-4" id="google_translate_element"></div>
            <script type="text/javascript">
							function googleTranslateElementInit() {
							  new google.translate.TranslateElement({pageLanguage: 'en', layout: google.translate.TranslateElement.InlineLayout.SIMPLE}, 'google_translate_element');
							}
						</script><script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
            </div>
        </div>
       
        <div class="row mb-3 mt-2 pt-3 footer-icons">
        
          <div class="col-lg-3 col-md-6 ml-auto text-center">
	          <a class="text-white" href="/discover-new-zealand/#" title="Become an ASURE Member Property">
	             <div class="social-icons m-auto p-3"><i class="fa fa-user fa-3x m-auto sr-contact"></i></div>
	            <p>
	            Become an ASURE Member Property
	            </p>
	          </a>
          </div>
          
          <div class="col-lg-3 col-md-6 mr-auto text-center">
            <a class="text-white" href="/about-us/mobile-app/" title="ASURE Accommodation Mobile App">
	             <div class="social-icons m-auto p-3"><i class="fas fa-mobile-alt fa-3x m-auto sr-contact"></i></div>
	            <p>
	              ASURE Accommodation Mobile App
	            </p>
            </a>
          </div>
          
          <div class="col-lg-3 col-md-6 mr-auto text-center">
            <a class="text-white" href="https://www.facebook.com/ASUREAccommodationGroupNZ/" target="_blank" title="ASURE Accommodation Group on Facebook">
	             <div class="social-icons m-auto p-3"><i class="fab fa-facebook-f fa-3x m-auto sr-contact"></i></div>
	            <p>
	              ASURE Accommodation Group on Facebook
	            </p>
            </a>
          </div>
          
          <div class="col-lg-3 col-md-6 mr-auto text-center">
            <a class="text-white" href="" target="_blank" title="ASURE Accommodation Group on Instagram">
	            <div class="social-icons m-auto p-3"><i class="fab fa-instagram fa-3x m-auto sr-contact"></i></div>
	            <p>
	              ASURE Accommodation Group on Instagram
	            </p>
            </a>
          </div>
          
        </div>
       
        
        <div class="row">
          <div class="col-lg-12 mx-auto text-center p-0">
            <span class="asure-cards">ASURE Accommodation Group Accepts All Major Credit Cards and: Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards.</span>
            <img class="img-fluid mb-5" src="images/ASURE_cards06.jpg" alt="Discover New Zealand" />
            </div>
        </div>
        
      </div>
    </section>
    
    <div class="footerCopy col-sm-12 text-center text-light p-3">
			<p class="m-0">&copy; %YEAR% -	<a class="text-light" href="/admin">Admin Login</a> - <a class="text-light" target="_blank" href="https://www.guesttraction.com/">Website by GuestTraction</a></p>
   </div>
    
    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded js-scroll-trigger" href="/discover-new-zealand/#page-top">
      <i class="fa fa-angle-up"></i>
    </a>

</div>

<script src="js/jquery-scrolltofixed-min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.headerBar').scrollToFixed();
    });
</script>