
<div id="footerBlock" class="removeFooter">
	<div class="row">	
		<div class="footerBlockCenter">
		<!--
			<div class="footerLogo">
				<a href="index.html" title="Bed and Breakfast Association NEW ZEALAND">
					<img src="images/logo_bandba1.png" title="Bed &amp; Breakfast Association NEW ZEALAND" alt="Bed &amp; Breakfast Association NEW ZEALAND" />
				</a>
			</div>
			<div class="font">Bed &amp; Breakfast Association NEW ZEALAND</div>
			<div class="footerTag">providing quality assessed hosted accommodation</div>
			-->
			<div class="footer-logo">
			<img src="images/footer-logo.png">
			</div>
			<div class="footerLinks">
				<a href="search.html" title="Bed and Breakfast Accommodation New Zealand">Search</a>
				<a href="regions.html" title="Browse Bed and Breakfast Accommodation">Browse by Region</a>
				<a href="about.html" title="About Bed and Breakfast Association New Zealand">About the B&amp;B Association</a>
				<a href="contact.html" title="Contact the Bed and Breakfast Association New Zealand">Contact</a>
				<a href="http://www.facebook.com/BedAndBreakfastAssociationNewZealand" title="Bed and Breakfast Association New Zealand on Facebook" class="last" target="_blank">
					<img src="images/logo_facebook.jpg" title="Bed &amp; Breakfast Association NEW ZEALAND on Facebook" alt="Facebook" />	
				</a>
			</div>
		</div>
	</div>
	<div id="footerCopy">	
		<div class="row">
			&copy; %YEAR% - 
			<a href="terms.html" title="Terms and Conditions">Terms and Conditions</a> - 
			<a href="sitemap.html" title="Site Map">Sitemap</a> - 	
			<a href="http://www.welman.co.nz/webrooms-login.asp" title="Login to Edit Your Website Profile" target="_blank" rel="nofollow">Edit Profile</a> -
			<a href="http://bandbassociation.co.nz/members/index.php" title="Login to Access the Member Area" target="_blank" rel="nofollow">Member Area</a> -
			<a href="http://www.guesttraction.com" title="Website Design" target="_blank" rel="nofollow">Website by GuestTraction</a>
		</div>
	</div>
</div>

