		
		<script src="js/jquery.cycle2.min.js"></script>
		<script src="js/jquery.cycle2.carousel.min.js"></script>
		<script src="js/jquery.cycle2.swipe.min.js"></script>		
		<script src="js/jquery.dotdotdot.min.js"></script>
		<script src="js/lightbox.min.js"></script>		
		<link href="css/lightbox.css" rel="stylesheet" />		
				
		<script src="js/moment.js" type="text/javascript"></script>
		<script src="js/jquery.daterangepicker.js" type="text/javascript"></script>
		
		<script src="js/js.js"></script>
		<script src="js/groupSearch.js"></script>
		<script src="%GLOBAL_ROOT%js/groupSearch_core.js"></script>
		<script src="%GLOBAL_ROOT%js/jquery.cookie.js"></script>
		
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyD5h6q7-T_tjnGPxRsSSVVgX71ckEjvgHA&libraries=places,geometry"></script>		
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800" rel="stylesheet" type="text/css"/>
		<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:700' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Yellowtail' rel='stylesheet' type='text/css'>
		
		<link rel="stylesheet" href="css/search.css" type="text/css"/>
		<link rel="stylesheet" href="css/daterangepicker.css" type="text/css"/>
		<link rel="stylesheet" href="css/map.css" type="text/css"/>
		<link rel="stylesheet" href="css/guest.css" type="text/css"/>
		<link rel="icon" type="image/png" href="images/favicon.png" />
		
		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		</style>
		
		%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
		
		<script> 
				$(document).ready(function() {
					$(".regionalPage .property-description").dotdotdot({
						ellipsis	: '... ',
					});
				});
		</script>
		
		<script>
			$(document).ready( function() {
		    $('div.reviews-cycle ul.event-list-inner').cycle({
					fx: 'fade',
					speed: 1100,
					timeout: 12000,
					slides: '> li'
				});
			});
		</script>
		
	</head>
	<body class="bodyStyle">
		