		
						
<div class="footerCopy">
		&copy; %YEAR% Primeproperty Group
			<span class="footerSpacer">|</span>
		<a href="sitemap.html">Site Map</a> 
			<span class="footerSpacer">|</span>
		<a href="http://www.welman.co.nz/webrooms-login.asp" rel="nofollow">Admin Login</a>
			<span class="footerSpacer">|</span>
		%CREDITLINK%
</div>

<script>
  var nav = responsiveNav(".nav-collapse");
</script>

