				
		
<div id="pageFooter">
	<div class="row">
		<div class="headerLeft">
			<a href="index.html" title="Motel Association of New Zealand" class="manzLogo">
				Motel Association of New Zealand
			</a>
		</div>
		<div class="headerRight">
    	<h2 class="siteTitle">%SITE_NAME%</h2>
	    <div class="nav1">
	    	%SITE_CUSTOM_CONTENT_1%
	    </div>
	    <div class="nav2">
	      %UL_NAV_1L%
	    </div>
	  </div>
  </div>
</div>
<div class="footerCopy">	
	&copy; %YEAR% Wellington Motel Association (MANZ) - <a href="sitemap.html">Site Map</a> - <a href="http://www.welman.co.nz/webrooms-login.asp">Admin Login</a>	
</div>


<script>
  var nav = responsiveNav(".nav-collapse");
</script>

