<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
<script src="js/jquery.cycle2.carousel.min.js"></script>
<script src="js/jquery.cycle2.swipe.min.js"></script>
<script src="js/responsive-nav.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/jquery.dotdotdot.min.js"></script>
<script src="js/js.js"></script>
<link href="css/lightbox.css" rel="stylesheet" />
<link href="css/responsive_1200grid.css" rel="stylesheet" />
<link href="css/fontface.css" rel="stylesheet" />
<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />

<script type="text/javascript" charset="utf-8" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&amp;sensor=false"></script>

		<script type="text/javascript">
			$(document).ready( function() {
			    $('#homeListings .property-list-outer').cycle({
							fx: 'carousel',
							timeout: 5000,
							carouselVisible: 4,
							slides: '> div',
							next: '.homePropNext',
							prev: '.homePropPrev'
					});
				} );
		</script>

<style>
%SITE_CUSTOM_CSS%
%PAGE_CUSTOM_CSS%
</style>

%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%

<!--[if lte IE 8]>
	<link rel="stylesheet" type="text/css" href="css/ie.css" />
<![endif]-->

<link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,300,400,600,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Roboto+Condensed:300italic,400italic,300,400,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Advent+Pro:100' rel='stylesheet' type='text/css'>

%SITE_CUSTOM_CONTENT_1%

<style>
			html, body { font-family:'colaborate-regularregular', sans-serif; font-size:15px; height:100%; }
</style>

</head>
	
<body class="pageBackground">

<div id="container">