
<div id="footerBlock">
	<div class="row">
	
		<div id="footerNav" class="remove">
			%UL_NAV_1L%
		</div>
		
		<div class="gold hLine"></div>
				
		<div class="row footerText">	
			<div class="columns six">
				<div class="footerCopy">
						&copy; %YEAR% Grandiose
							<span class="footerSpacer">|</span>
						<a href="sitemap.html">Site Map</a> 
							<span class="footerSpacer">|</span>
						<a href="https://secure.web-rooms.co.nz" rel="nofollow">Admin Login</a>
							<span class="footerSpacer">|</span>
						<a href="http://www.welman.co.nz" title="Web Site Built by Welman Technologies Ltd" target="_blank" rel="nofollow">Built by Welman Technologies</a>
				</div>
			</div>
			<div class="columns six">
			<!--
				<div class="newsletterSub">
					Subscribe to Newsletter
				</div>
			-->
			</div>
		</div>
		
	</div>
</div>

</div>

</body>

<script>
  var nav = responsiveNav(".nav-collapse");
</script>
