	<div id="headerBlock">
		
		<div class="propertyLogo">
			<a href="/" title="Grandiose">
				<img src="images/logo_grandiose-new2.png" alt="Grandiose" />
			</a>
		</div>
		
		<div class="gold hLine"></div>
		
		<div id="headerNav">
			<nav class="nav-collapse">
				%UL_NAV_1L%
			</nav>
	  </div>
	  
	  <div class="gold hLine"></div>
	  
		<div class="propertyBook">
	   %JQUERY_DATE_PICKER_CUSTOM_PAGE["Arrival Date:","Book Now","accommodation.html"]%
	  </div>
		
	</div>