			</div>
		</div>
	</div>
	
	<div id="footerContent">
		<div class="row">
			<div class="columns six">
				<div class="propertyInfo">
						<h3 class="font"><a href="%SITE_URL%" title="%PROPERTY_NAME%">%PROPERTY_NAME%</a></h3>
						<div class="propertyAddress">%PROPERTY_STREETADDRESS%</div><div class="propertySuburb">, %PROPERTY_SUBURB%</div><div class="propertyCity">, %PROPERTY_CITY%</div><div class="propertyRegion">, %PROPERTY_REGION%</div><br />
						<div class="propertyFreephone">%PROPERTY_FREEPHONE_LABEL%</div><div class="dash"> - </div><div class="propertyPhone">%PROPERTY_TOLLPHONE_LABEL%</div> <div class="remove"><br /></div>
						<div class="propertyEmail">Email <a href="mailto:%RESERVATIONS_EMAIL%">%RESERVATIONS_EMAIL%</a></div>
						<div class="socialIcons">%FACEBOOK_PAGELINK% %TWITTER_PAGELINK% %GOOGLEPLUS_PAGELINK%</div>
				</div>
			</div>
			<div class="columns six">
				<div class="footerBadges">
					%SITE_CUSTOM_CONTENT_3%
				</div>
			</div>
		</div>
	</div>

</div>

<div id="footerNav" class="remove">
	<div class="row">
			%UL_NAV_1L%
	</div>
</div>

<div id="footerCopy">
	&copy; %YEAR% %PROPERTY_NAME% - 
	<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
	<a href="http://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
	%CREDITLINK%
</div>

<script type="text/javascript">
  var nav = responsiveNav(".nav-collapse");
</script>