/* book online */
.bookingBox { padding:25px 0; text-align:center; }
.bookText { display:inline-block; vertical-align: middle; font-size:24px; margin-right:10px; font-weight:300; }
.webrooms-datepicker { position:relative; display:inline-block; vertical-align: middle; }
.bookingBox .datepicker-label,
.bookingBox .datepicker-input,
.bookingBox .datepicker-button,
.bookingBox .datepicker-label:before { line-height:45px; height:45px; }
.bookingBox .datepicker-button { font-family:'Source Sans Pro', sans-serif; color:#fff; display:inline-block; border-radius:4px; border:none; cursor:pointer;
		text-transform:uppercase; font-size:18px; font-weight:800; padding-right:40px; position:relative; margin-left:10px; }
.datepicker-button:hover { opacity:0.8; }
.datepicker-button:before { content:''; background:url(../images/background_booking.png) no-repeat center center; background-size:16px; width:16px; height:16px; position:absolute; top:0; height:45px; right:15px; }
#ui-datepicker-div { z-index:9999 !important; font-size:100%; }

/* home */		
.pageCustom1 { padding-bottom:20px; }
.homeContainer { }

@media only screen and (max-width: 960px) 
{
.homeArticles { margin:0; }
.pageCustom1 { padding-bottom:1.5em; }
}

@media only screen and (max-width: 640px) 
{

}