<div id="footerBlock">
	<div class="row">	
		<div id="footerContent">
				<div class="propertyLogo"></div> <!-- area to add your custom logo via css -->
				<div class="contactInfo">	
					<h3 class="font"><a href="/" title="%PROPERTY_NAME%">%PROPERTY_NAME%</a></h3>
					<div class="footerContact">
						<div class="propertyAddress">%PROPERTY_STREETADDRESS%</div><div class="propertySuburb">, %PROPERTY_SUBURB%</div><div class="propertyCity">, %PROPERTY_CITY%</div><div class="propertyRegion">, %PROPERTY_REGION%</div><div class="propertyCountry">, %PROPERTY_COUNTRY%</div><br class="remove" />
						<div class="propertyFreephone">%PROPERTY_FREEPHONE_LABEL%</div><div class="dash"> - </div><div class="propertyPhone">%PROPERTY_TOLLPHONE_LABEL%</div><br class="remove" />
						<div class="propertyEmail">Email <a href="mailto:%RESERVATIONS_EMAIL%">%RESERVATIONS_EMAIL%</a></div>
					</div>
				</div>
				<div class="footerBadges">
					%SITE_CUSTOM_CONTENT_2%
				</div>
		</div>
		<div id="footerCopy">
			<div class="social">%FACEBOOK_PAGELINK% %TWITTER_PAGELINK% %GOOGLEPLUS_PAGELINK% %TRIPADVISOR_PAGELINK%</div>
			<div class="copyright">
				&copy; %YEAR% %PROPERTY_NAME% - 
				<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
				<a href="https://secure.web-rooms.co.nz/Login.asp" title="Admin Login">Admin Login</a> - 
				%CREDITLINK%
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
var nav = responsiveNav(".nav-collapse");
</script>

<script src="js/jquery-scrolltofixed-min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('#headerBlock').scrollToFixed();
    });
</script>