<footer class="footerBlock">
	<section class="newsletter">
			<div class="container">
				<h2>Stay Informed</h2>
				<!-- <h3>Sign up to receive our Newsletter!</h3>
				<a href="/newsletter.html" type="submit" class="btn btn-default">Subscribe</a>	-->
				
							
				<!-- Begin MailChimp Signup Form -->
				<link href="//cdn-images.mailchimp.com/embedcode/horizontal-slim-10_7.css" rel="stylesheet" type="text/css">
				<style type="text/css">
					#mc_embed_signup{clear:left; font:14px Helvetica,Arial,sans-serif; width:100%;}
					#mce-EMAIL {height:45px !important;}
				</style>
				<style type="text/css">
					#mc-embedded-subscribe-form input[type=checkbox]{display: inline; width: auto;margin-right: 10px;}
					#mergeRow-gdpr {margin-top: 20px;}
					#mergeRow-gdpr fieldset label {font-weight: normal;}
					#mc-embedded-subscribe-form .mc_fieldset{border:none;min-height: 0px;padding-bottom:0px;}
					#mc-embedded-subscribe {background-color:#ff4a00;font-weight:900;color:#fff;}
				</style>
				<div id="mc_embed_signup">
				<form action="https://bnblive.us15.list-manage.com/subscribe/post?u=0431bfcef0008a9e1c1156f59&amp;id=25f771b778" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
				    <div id="mc_embed_signup_scroll">
					<label for="mce-EMAIL"><h3>Sign up to receive our Newsletter!</h3></label>
					<input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="email address" required>
				    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
				    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_0431bfcef0008a9e1c1156f59_25f771b778" tabindex="-1" value=""></div>
				    <div class="clear"><input type="submit" value="Subscribe" name="subscribe" id="mc-embedded-subscribe" class="btn btn-default"></div>
				    </div>
				</form>
				</div>

				<!--End mc_embed_signup-->
			</div>
	</section>
		
	<section class="footerbott">
		<div class="container">

			<div class="row">
				<div class="col-sm-3 footercon">
					<h4>Bnblive.com</h4>
					<ul class="footerlist">
						<li><a href="search.html">Search</a></li>
						<li><a href="guest-dashboard.html">Create a Guest Profile</a></li>
						<li><a href="list-your-property.html">List your Accommodation Property</a></li>
						<li><a href="contact.html">Contact Us</a></li>
						<li><a href="host-login.html">Property Login</a></li>
					</ul>
				</div>
				<div class="col-sm-2 footercon">
					<h4>Site Info</h4>
					<ul class="footerlist">
						<li><a href="about-us.html">About Us</a></li>
						<!--<li><a href="host-guarantee.html">Host Guarantee</a></li>-->
						<!--<li><a href="guest-guarantee.html">Guest Guarantee</a></li>-->
						<li><a href="terms-conditions.html">Terms &amp; Conditions</a></li>
						<li><a href="faq.html">FAQ </a></li>
					</ul>
				</div>
				<div class="col-sm-4 footercon">
				  <div class="news-area">
				  <h4>Latest News</h4>
					%EVENTS_BY_EVENTCATEGORY_TEASERS_TEMPLATE_CONFIGNAME["eventCategoryId_events","News.template","eventCategoryId"]%
					</div>
				</div>
				<div class="col-sm-3 footercon">
					<h4>Quick Contact</h4>
					<p><i class="fa fa-envelope-o" aria-hidden="true"></i>
						<a href="mailto:admin@bnblive.com">admin@bnblive.com</a>
					</p>
					<p><i class="fa fa-mobile" aria-hidden="true" style="font-size:20px;"></i>
						NZ: 0800 400 900
					</p>
				</div>
			</div>

			<section class="joinus">
				<h4>Join Us On</h4>
				<a href="https://www.facebook.com/rentalsbnb/" target="_blank"><span class="socialicon"><i class="fa fa-facebook" aria-hidden="true"></i></span></a>
				<a href="https://www.twitter.com/bnblivelimited" target="_blank"><span class="socialicon"><i class="fa fa-twitter" aria-hidden="true"></i></span></a>
				<div class="copyright">
						&copy; BnBlive %YEAR% - 
						<a href="sitemap.html" title="Website Site Map">Sitemap</a> -					
						<a href="https://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
						<a href="https://www.guesttraction.com" title="Website Designed by GuestTraction" target="_blank" rel="nofollow">Maintained by GuestTraction</a>
				</div>
			</section>
		</div>
		<div>%SITE_CUSTOM_CONTENT_2%</div>
	</section>
</footer>

<!-- js -->	
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/jquery.dotdotdot.min.js"></script>

<!-- css -->	
<link href="css/lightbox.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- scripts -->
<script type="text/javascript">
		$(document).ready(function() {
			$(".ellipsis").dotdotdot({
				ellipsis	: '... ',
			});
		});
</script>