<script type="text/javascript" src="js/moment.js"></script>
<script type="text/javascript" src="js/jquery.daterangepicker.js"></script>
<script type="text/javascript" src="js/js.js"></script>
<script type="text/javascript" src="js/groupSearch.js"></script>
<script type="text/javascript" src="%STATIC_WEBROOMSCDN_URL%js/groupSearch_core.js"></script>
<script type="text/javascript" src="%STATIC_WEBROOMSCDN_URL%js/jquery.cookie.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&libraries=places,geometry"></script>		
%WEBROOMS_JS_INCLUDE%

<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="css/bnblive.css">
<link rel="stylesheet" type="text/css" href="css/menu.css">
<link rel="stylesheet" type="text/css" href="css/search.css">
<link rel="stylesheet" type="text/css" href="css/daterangepicker.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/css_roomtypes_16v2.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/css_datepicker_16v2.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/font-awesome/css/font-awesome.min.css">

<style>
	%SITE_CUSTOM_CSS%
	%PAGE_CUSTOM_CSS%
</style>

%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
<link rel="stylesheet" type="text/css" href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,700,800'>
%SITE_CUSTOM_CONTENT_1%

<meta name="google-site-verification" content="GZuJMHbPjIfW3Y_dggIZEls8fr-jPy1DOqAZYSzb2TQ" />

</head>
<body class="bodyStyle">

<header class="outerheader innerpage">
	<section class="topheader">
	    <aside class="logopart">
        <div class="logopic"><a href="index.html"><img src="images/logo.png" alt="BnbLive"></a></div>
        <div class="logocap">accommodation made easy</div>
        <div class="clear"></div>
	    </aside>
	    <nav> 
        <div class="clearfix"></div>
        <ul class="navi">
            <li><a href="index.html"><i class="fa fa-home" aria-hidden="true"></i></a></li>
            <li><a href="list-your-property.html">List your property</a></li>
        </ul>
	    </nav>
	    <div class="clear"></div>
	</section>
</header>

%GROUP_GUEST_LOGIN%