<div id="footerNav" class="remove">
	<div class="row">
			%UL_NAV_1L%
	</div>
</div>

	<div id="footerContainer">
			<div class="row">
				<div class="columns six">
						<div id="footerContact">
							<h4 class="font">%PROPERTY_NAME%</h4>
							<div class="propertyAddress">%PROPERTY_STREETADDRESS%</div><div class="propertyCity">, %PROPERTY_CITY%</div><div class="propertyRegion">, %PROPERTY_REGION%</div><br />
							<div class="propertyFreephone">%PROPERTY_FREEPHONE_LABEL%</div><div class="dash"> - </div><div class="propertyPhone">%PROPERTY_TOLLPHONE_LABEL%</div> <div class="remove"><br /></div>
							<div class="propertyEmail">Email <a href="mailto:%RESERVATIONS_EMAIL%">%RESERVATIONS_EMAIL%</a></div>
						</div>
				</div>
				<div class="columns six">
						<div id="footerCustom1">
							<div class="hostRewards">
								<div class="hostCard"></div>
								<h4>Host Rewards - Join, Stay &amp; Save</h4>
								<p>%PROPERTY_NAME% is proud to be a member of the Host Accommodation Group. With over 80 properties throughout the country choose a Host property for your next stay and earn Host Reward points.
										<a target="_blank" title="Host Accommodation Rewards" href="http://hostrewards.co.nz/">http://hostrewards.co.nz/</a></p>
							</div>
						</div>
				</div>
			</div>
			<div id="footerCopy">
				&copy; %YEAR% %PROPERTY_NAME% - 
				<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
				<a href="http://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
				%CREDITLINK%
			</div>
	</div>
	
	<div id="footerCustom2">
		<div class="row">
			<div class="hostStrip">
				<div class="hostLinks">
					<ul>
						<li><a target="_blank" href="http://www.hostaccommodation.co.nz/">About HOST</a></li>
						<!--<li><a target="_blank" href="http://hostrewards.co.nz/">HOST Rewards</a></li>-->
					</ul>
				</div>
			</div>
		</div>
	</div>

<script type="text/javascript">
  var nav = responsiveNav(".nav-collapse");
</script>