<footer class="footer text-center">
      <div class="container">
        <div class="row">
        
          <div class="col-md-4 mb-5 mb-lg-0 text-left">
            <h4 class="text-uppercase mb-4">KiwiCamp</h4>
            <ul class="list-inline">
		          
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%" title="Find KiwiCamps">Find KiwiCamps</a>					  
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%how-it-works/" title="How it works">How it works</a>						  
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%what-is-kiwi-camp/" title="What is KiwiCamp">What is KiwiCamp</a>						  
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%why-use-kiwicamp/" title="What is KiwiCash">What is KiwiCash</a>						  
								<li class="current"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%find-a-key/" title="Find A Key">Find A Key</a>						  
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%get-a-kiwicamp/" title="More info">Get a KiwiCamp facility</a>						  
								<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%contact-us/" title="Contact">Contact</a>
						  
            </ul>
          </div>
          
          <div class="col-md-4 mb-5 mb-lg-0">
	          
	            <h4 class="text-uppercase mb-4">Contact us</h4>
	            <span>Phone: <a href="tel:050854942274" class="text-white">0508 5494 2274</a></span><br>
	            <span>Email: <a href="mailto:help@kiwicash.nz" class="text-white">help@kiwicash.nz</a></span><br>
	            <span>Address: See home page for camp locations.</span><br>
	            <span><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%privacy-policy">Privacy Policy</a></span><br>
	            <span><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%how-it-works/terms-of-use/">Terms of Use</a></span>

	           
	          </div>
	          <div class="col-md-4 text-right social-list">
	            <h4 class="text-uppercase mb-4">Follow us</h4>
	            
	             <ul class="list-inline mb-0">
	              <li class="list-inline-item">
	                <a class="btn btn-outline-light btn-social text-center rounded-circle" target="_blank" href="https://www.facebook.com/kiwicampnz/">
	                  <i class="fab fa-facebook-f"></i>
	                </a>
	              </li>
	              <li class="list-inline-item">
	                <a class="btn btn-outline-light btn-social text-center rounded-circle" target="_blank" href="https://www.instagram.com/KiwiCampNZ/">
	                  <i class="fab fa-instagram"></i>
	                </a>
	              </li>
	            </ul>

	           
	         </div>
            
        </div>
      </div>
    </footer>

    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; 2018 - <a href="/admin/" class="text-light">Admin Login</a> - <a class="text-light" href="https://www.guesttraction.com/" target="_blank">Website by GuestTraction</a></small>
      </div>
    </div>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="/about-us/#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>


<!-- js -->	
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/jquery.dotdotdot.min.js"></script>

<!-- css -->	
<link href="css/lightbox.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- scripts -->
<script type="text/javascript">
		$(document).ready(function() {
			$(".ellipsis").dotdotdot({
				ellipsis	: '... ',
			});
		});
</script>