/* background */
.propertyInfo { margin:45px auto 0; padding:0; }

/* book online */
.bookingBox { padding:150px 0 200px 0; margin:0; text-align:center; }
.bookText { display:inline-block; color:#75dcfc; vertical-align: middle; font-size:24px; margin-right:10px; font-weight:300; }
.webrooms-datepicker { position:relative; display:inline-block; vertical-align: middle; }
.datepicker-label:before { left:12px; }
.bookingBox .datepicker-label,
.bookingBox .datepicker-input,
.bookingBox .datepicker-button,
.bookingBox .datepicker-label:before { line-height:55px; height:55px; font-size:16px; }
.bookingBox .datepicker-label { width:320px; line-height:57px; text-indent:35px; }
.bookingBox .datepicker-input { width:190px; left:110px; }
.bookingBox .datepicker-button { font-family:'Source Sans Pro', sans-serif; color:#fff; display:inline-block; border-radius:0; cursor:pointer;
		text-transform:uppercase; font-size:18px; font-weight:800; padding:0 30px; position:relative; margin-left:10px; height:57px; }
.datepicker-button:hover { opacity:0.8; }
#ui-datepicker-div { z-index:9999 !important; font-size:100%; }

/* home */		
.pageCustom1 { padding-bottom:20px; }
.homeContainer { margin-top:20px; position:relative; }

@media only screen and (max-width: 960px) 
{
.homeArticles { margin:0; }
.pageCustom1 { padding-bottom:1.5em; }
.bookingBox .datepicker-label,
.bookingBox .datepicker-button { width:100%; padding:0; margin:2px auto; }
#headerBlock .headerIcons { display:block; position:static; margin:auto auto 2em; }
}

@media only screen and (max-width: 640px) 
{

}