<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" >
		<meta name="keywords" content="%PAGE_KEYWORDS%" >
		<meta name="description" content="%PAGE_DESCRIPTION%" >
		<meta name="author" content="GuestTraction - Smart Sites - www.guesttraction.com" >
			
			
		<meta name="viewport" content="width=device-width,initial-scale=1" >
		<title>%PAGE_TITLE%</title>
		<link rel="canonical" href="%SITE_URL%/%PAGE_URL%" />
		<link rel="shortcut icon" type="image/x-icon" href="images/favicon.ico" />
		
			
		%JQUERY_INCLUDES%
		
		%TEMPLATE_CSS%
		
		%RECAPTCHA_INCLUDES%