<!-- Footer -->
    <footer class="footer text-center">
      <div class="container">
        <div class="row">
          <div class="col-md-4 mb-5 mb-lg-0 text-left">
            <h4 class="text-uppercase mb-4">Central Reservations </h4>
            <ul class="list-inline">
	          
							<li class="current"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%" title="Home">Home</a>
					  
							<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%locations/" title="Our Property Locations">Locations</a>
					  
							<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%about-us/" title="About Us">About Us</a>
					  
							<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%contact-us/" title="Contact Us">Contact Us</a>
					  
							<li class="link"><a class="menu-list text-white" href="%SITE_CUSTOM_CONTENT_3%things-to-do-in-new-zealand/" title="Things to do in New Zealand">New Zealand</a>
					  
					  <li><a class="menu-list text-white" target="_blank" href="/assets/Uploads/430b7dee55/CRNZ-Terms-Conditions-v2.pdf">Terms & Conditions</a></li>
					  <li><a class="menu-list text-white" target="_blank" href="/assets/Uploads/385b2a2695/CRNZ-Privacy.pdf">Privacy Policy</a></li>
          </ul>
          </div>
          <div class="col-md-4 mb-5 mb-lg-0">
          
            <h4 class="text-uppercase mb-4">Contact us</h4>
            <span>Phone: <a href="tel:+64068684052" class="text-white">+64 (0)6 868 4052</a></span><br>
            <span>Email: <a href="mailto:res@centralres.co.nz" class="text-white">res@centralres.co.nz</a></span><br>
            <span>Address: 193 Cobden Street,<br />Gisborne, 4010, New Zealand</span>
           
          </div>
          <div class="col-md-4 text-right social-list">
            <h4 class="text-uppercase mb-4">Follow us</h4>
            
            <ul class="list-inline mb-0">
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" target="_blank" href="https://www.facebook.com/centralres.accommodation">
                  <i class="fab fa-facebook-f"></i>
                </a>
              </li>
              <li class="list-inline-item">
	                <a class="btn btn-outline-light btn-social text-center rounded-circle" target="_blank" href="https://www.instagram.com/centralres.co.nz/">
	                  <i class="fab fa-instagram"></i>
	                </a>
	              </li>
            </ul>
            
        </div>
      </div>
    </footer>

    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; %YEAR% - <a href="/admin/" class="text-light">Admin Login</a> - <a class="text-light" href="https://www.guesttraction.com/" target="_blank">Website by GuestTraction</a></small>
      </div>
    </div>

    <!-- Scroll to Top Button (Only visible on small and extra-small screen sizes) -->
    <div class="scroll-to-top d-lg-none position-fixed ">
      <a class="js-scroll-trigger d-block text-center text-white rounded" href="/#page-top">
        <i class="fa fa-chevron-up"></i>
      </a>
    </div>



<!-- js -->	
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/jquery.dotdotdot.min.js"></script>

<!-- css -->	
<link href="css/lightbox.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- scripts -->
<script type="text/javascript">
		$(document).ready(function() {
			$(".ellipsis").dotdotdot({
				ellipsis	: '... ',
			});
		});
</script>