<script type="text/javascript" src="js/moment.js"></script>
<script type="text/javascript" src="js/jquery.daterangepicker.js"></script>
<script type="text/javascript" src="js/js.js"></script>
<script type="text/javascript" src="js/groupSearch.js"></script>
<script type="text/javascript" src="%STATIC_WEBROOMSCDN_URL%js/groupSearch_core.js"></script>
<script type="text/javascript" src="%STATIC_WEBROOMSCDN_URL%js/jquery.cookie.js"></script>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA2EKm8Aw1T3m6mIZyemjQHjk3x_AF1Oi0&libraries=places,geometry"></script>		
%WEBROOMS_JS_INCLUDE%

<link rel="stylesheet" type="text/css" href="css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="css/custom.css">
<link rel="stylesheet" type="text/css" href="css/menu.css">
<link rel="stylesheet" type="text/css" href="css/search.css">
<link rel="stylesheet" type="text/css" href="css/daterangepicker.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/css_roomtypes_16v2.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/css_datepicker_16v2.css">
<link rel="stylesheet" type="text/css" href="%STATIC_WEBROOMSCDN_URL%websites/common/css/font-awesome/css/font-awesome.min.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css">

<!-- Bootstrap -->
<link rel="stylesheet" type="text/css" href="https://www.centralres.co.nz/resources/themes/centralres/vendor/bootstrap/css/bootstrap.min.css">
<script src="js/bootstrap.bundle.js"></script>

<style>
	%SITE_CUSTOM_CSS%
	%PAGE_CUSTOM_CSS%
</style>

%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
<link href="https://fonts.googleapis.com/css?family=Roboto:400,700" rel="stylesheet">

%SITE_CUSTOM_CONTENT_1%

</head>
<body class="bodyStyle">

 <!-- Navigation -->
    <nav class="navbar navbar-expand-lg bg-white fixed-top text-uppercase" id="mainNav">
      <div class="container-fluid">
	      
		      
			      	<a href="%SITE_CUSTOM_CONTENT_3%" class="logo d-none d-lg-block"><img src="images/logo.jpg" title="Central Reservations " alt="Central Reservations "></a>
			      		
		          <h6 class="d-block d-md-none mb-0">Central Reservations</h6>
	      
        <button class="navbar-toggler navbar-toggler-right text-uppercase bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fa fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
	          
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="%SITE_CUSTOM_CONTENT_3%" title="Home">Home</a>									  
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="%SITE_CUSTOM_CONTENT_3%locations/" title="Our Property Locations">Locations</a>				  
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="%SITE_CUSTOM_CONTENT_3%about-us/" title="About Us">About Us</a>		  
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="%SITE_CUSTOM_CONTENT_3%contact-us/" title="Contact Us">Contact Us</a>			  
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="%SITE_CUSTOM_CONTENT_3%things-to-do-in-new-zealand/" title="Things to do in New Zealand">New Zealand</a>
							<li class="link nav-item mx-0 mx-lg-2"><a class="menu-list nav-link px-lg-3 px-1 rounded" href="https://book.centralres.co.nz" title="Search">Search</a> 
					  
          </ul>
          <a class="btn btn-plain" href="https://centralres.web-rooms.com">Guest Login</a>
        </div>
      </div>
    </nav>