<div id="footerNav" class="remove">
	<div class="row">
			%UL_NAV_1L%
	</div>
</div>

	<div id="footerContainer">
			<div class="row">
				<div class="columns six">
						<div id="footerContact">
							<h4 class="font">%PROPERTY_NAME%</h4>
							%PROPERTY_STREETADDRESS%, %PROPERTY_CITY%<span class="propertyRegion">, %PROPERTY_REGION%</span><br />
							%PROPERTY_FREEPHONE_LABEL% <span class="dash">-</span> %PROPERTY_TOLLPHONE_LABEL%<br />
							Email <a href="mailto:%RESERVATIONS_EMAIL%">%RESERVATIONS_EMAIL%</a> <br />
						</div>
				</div>
				<div class="columns six">
						<div id="footerCustom1">
								%SITE_CUSTOM_CONTENT_3%
						</div>
				</div>
			</div>
			<div id="footerCopy">
				Copyright &copy; %YEAR% %PROPERTY_NAME% - 
				<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
				<a href="https://secure.web-rooms.co.nz/Login.asp" title="Admin Login">Admin Login</a> - 
				%CREDITLINK%
			</div>
	</div>

<script type="text/javascript">
  var nav = responsiveNav(".nav-collapse");
</script>