
<div id="footerNav" class="remove">
	<div class="row">
			%UL_NAV_1L%
	</div>
</div>

<div id="footerBlock">

	<div id="footerContent">
		<div class="row">
			<div class="columns six">
				<div class="propertyInfo">
						<h3 class="font"><a href="%SITE_URL%" title="%PROPERTY_NAME%">%PROPERTY_NAME%</a></h3>
						<div class="propertyAddress">%PROPERTY_STREETADDRESS%</div><div class="propertySuburb">, %PROPERTY_SUBURB%</div><div class="propertyCity">, %PROPERTY_CITY%</div><div class="propertyRegion">, %PROPERTY_REGION%</div><br />
						<div class="propertyFreephone">%PROPERTY_FREEPHONE_LABEL%</div><div class="dash"> - </div><div class="propertyPhone">%PROPERTY_TOLLPHONE_LABEL%</div> <div class="remove"><br /></div>
						<div class="propertyEmail">Email <a href="mailto:%RESERVATIONS_EMAIL%">%RESERVATIONS_EMAIL%</a></div>
						<div class="contact-section">%SITE_CUSTOM_CONTENT_3%</div>
				</div>
			</div>
			<div class="columns six">
				<div class="footerBadges">
					%SITE_CUSTOM_CONTENT_2%
				</div>
			</div>
		</div>
	</div>
	
<div class="hostBottom">
	<div class="row posRel">
		<div class="hostLeft"></div>
		<div class="hostText">
			<p>Member of Host Accommodation Group.  With over 80 properties throughout the country choose a Host Property for your next stay and earn Host Reward Dollars. <a href="https://www.hostaccommodation.co.nz/" target="_blank">www.hostaccommodation.co.nz</a></p>
		</div>
		<div class="hostLink">
			<a target="_blank" href="https://www.hostaccommodation.co.nz/"><span class="info-icon"></span> About HOST</a>
		</div>
		<div class="hostRight"></div>
	</div>
</div>
	
	<div id="footerCopy">
		&copy; %YEAR% %PROPERTY_NAME% - 
		<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
		<a href="https://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
		%CREDITLINK%
	</div>

</div>

</div>

<script>
  var nav = responsiveNav(".nav-collapse");
</script>