

<div class="row" id="removeFooter">
	<div id="footerBlock">
	
		<div class="footerCenter">
			<span class="footerTag">Stay Rotorua is powered by</span>
				<a href="index.html" title="Rotorua Association of Motels" class="ramLogo">
					Rotorua Association of Motels
				</a>
			<a href="about.html" title="Rotorua Associaiton of Motels">About RAM</a> <span class="footerLinkBorder">|</span>	
			<a href="contact.html" title="Contact">Contact</a>	<span class="footerLinkBorder">|</span>				
			<a href="sitemap.html" title="Sitemap">Sitemap</a>
	  </div>	
	
		<div class="footerLeft">
			<a class="btn" href="http://www.welman.co.nz/webrooms-login.asp" title="RAM Member Login" target="_blank">
				RAM Member Login
			</a>
		</div>
	
		<div class="footerRight">	
			&copy; %YEAR% R.A.M. <br />
			%CREDITLINK%
		</div>
	
	</div>
</div>
