
<script src="js/jquery.cycle2.min.js"></script>
<script src="js/jquery.cycle2.carousel.min.js"></script>
<script src="js/jquery.cycle2.swipe.min.js"></script>		
<script src="js/jquery.dotdotdot.min.js"></script>
<script src="js/lightbox.min.js"></script>		
<link href="css/lightbox.css" rel="stylesheet" />		

<script src="js/moment.js"></script>
<script src="js/jquery.daterangepicker.js"></script>
		
<script src="js/js.js"></script>
<script src="js/groupSearch.js"></script>
<script src="%STATIC_WEBROOMSCDN_URL%js/groupSearch_core.js"></script>
<script src="%STATIC_WEBROOMSCDN_URL%js/jquery.cookie.js"></script>

<script src="https://www.goldenchain.com.au/resources/themes/goldenchain/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAysyjHrNW47nzpKIH1LhUlpq5_drnetzI&libraries=places,geometry"></script>		
<script src="%STATIC_WEBROOMSCDN_URL%js/markerClusterer.js"></script>

<link rel="stylesheet" href="css/search.css" type="text/css"/>
<link rel="stylesheet" href="css/daterangepicker.css" type="text/css"/>
<link rel="stylesheet" href="css/forms.css" type="text/css"/>

<link href="css/font-awesome/css/font-awesome.css" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Oswald:500&display=swap" rel="stylesheet">

<link rel="stylesheet" href="https://www.goldenchain.com.au/resources/themes/goldenchain/vendor/bootstrap/css/bootstrap.min.css" type="text/css"/>
<link rel="stylesheet" href="https://www.goldenchain.com.au/resources/themes/goldenchain/css/custom.css" type="text/css"/>

<link rel="icon" type="image/ico" href="images/favicon.ico" />
%SITE_CUSTOM_CONTENT_4%

<style>
%SITE_CUSTOM_CSS%
%PAGE_CUSTOM_CSS%
</style>
<script>
$(document).ready(function() {
	$(".GC .result-outer .result-description").dotdotdot({
		ellipsis	: '... ',
	});
});
</script>
<script>
function myFunction() {
    var x = document.getElementById("GC-Topnav");
    if (x.className === "topnav") {
        x.className += " responsive";
    } else {
        x.className = "topnav";
    }
}
</script>


%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%

</head>
<body class="bodyStyle">
 		%SITE_CUSTOM_CONTENT_3%
 		%SITE_CUSTOM_CONTENT_1%
