<section id="contact" class="bg-primary text-white footerBlock">
    
      <div class="container">

          <div class="col-12">
           <div class="row">
            <div class="col-md-4 text-left">
		          
		             
		          	 		<img class="" src="%SITE_CUSTOM_CONTENT_2%/assets/Logos/231d344d3d/Golden-Chain-logo-PNG__ScaleHeightWzgwXQ.png" title="Golden Chain logo PNG" alt="Golden Chain logo PNG">
		          	 
			           
			       </div>
			       
			       <div class="col-md-4 text-left">
				       <h3>Quick Links</h3>
				       <ul class="">
					       <li><a class="text-white" title="Looking for accommodation" href="%SITE_CUSTOM_CONTENT_2%/properties/search.html">Search</a></li>
					       <li><a class="text-white" title="Guest Login" href="https://goldenchain.web-rooms.com">Guest Login</a></li>
					       <li><a class="text-white" title="Become a member" href="%SITE_CUSTOM_CONTENT_2%/looking-to-belong/">Become a Member</a></li>
				       </ul>
			       </div> 
			       
			       
			       <div class="col-md-4 text-left">
				       <h3>Contact Us</h3>
				       <p>Address: Golden Chain Motor Inns Ltd<br />
PO Box 5220, Port Macquarie, NSW 2444 
				       <br>Phone: <a class="text-white" href="tel:0292112377">02 9211 2377</a><br>
				       TollFree: <a class="text-white" href="tel:1800023966">1800 023 966</a></p>
			       </div>
			               
			     </div>
          </div>
          
          <div class="col-12">
          	
          </div>
          
          <div class="col-12 border-top pt-3">        
	          <ul class="list-inline m-auto social-buttons text-center">
	          
						     <li class="list-inline-item text-center">
						         <a class="btn btn-social text-center rounded-circle" target="_blank" href="https://www.facebook.com/GoldenChainMotelsAustralia/">
						           <i class="fa fa-facebook"></i>
						        </a>
						     </li>
						  	
						  
						     <li class="list-inline-item text-center">
						         <a class="btn btn-social text-center rounded-circle" target="_blank" href="https://www.instagram.com/goldenchainmotels/">
						           <i class="fa fa-instagram"></i>
						        </a>
						     </li>
						  						  			      	
						</ul>
         </div>

      </div>
    
  </section>
  
  <div class="footerCopy col-sm-12 text-center bg-dark text-white py-3">
		<p class="m-0">&copy; 2019 -	<a class="text-white" href="/admin">Admin Login</a> - <a class="text-white" href="%SITE_CUSTOM_CONTENT_2%/sitemap.xml">Sitemap</a> - <a class="text-white" target="_blank" href="https://www.guesttraction.com/">Website by GuestTraction</a></p>
  </div>


<script src="js/jquery-scrolltofixed-min.js"></script>
<script>
    $(document).ready(function() {
        $('.headerBar').scrollToFixed();
    });
</script>