

@media only screen and (max-width: 960px) 
{
	#headerContainer { background-size:cover; }
#headerContact { display:block; }
#headerContact .icoLocation, 
#headerContact .icoPhone { background:none; padding:none; text-align:center; text-shadow:none; color:#fff; display:block; }
#headerContact .icoLocation div, 
#headerContact .icoPhone div { display:inline-block; }	
	#headerMiddle { padding:2em; padding-top:0; }
	#headerBooking { padding:1em 0; }
  #headerLogo h3 { display:block; text-align:center; font-size:300% !important; padding:1em 1em 0 1em; position:static; line-height:100%; }
  #headerLogo h3 a { color:#fff }
	.datepicker-input { display:block; width:100%; text-align:center; padding:5px 0; margin:5px 0; border-radius:0; }
	.datepicker-button { width:100%; background-position:left center !important; width:100%; background-position:15px center !important; text-align:center; padding:1em 2em; }
}
















