
<div id="footerBlock">
	<div class="row">
			<div class="columns four">
				<div class="footerLoyalty">
					<h4>About ASURE</h4>
					<p>The ASURE Accommodation Group consists of quality accommodation properties throughout New Zealand.</p>
					<a class="btn" href="ASURE.html" title="About ASURE Accommodation">About ASURE</a>
				</div>
			</div>
			<div class="columns four">
				<!-- loyaltycard referenced from ASUREstay.com -->
				<div class="footerLoyalty">
					<h4>ASURE Loyalty Programme</h4>
					<p>Stay at three or more ASURE Accommodation Group properties and receive $100 credit off your 10th stay!</p>
					<a class="btn" href="http://www.ASUREstay.com" target="_blank" title="Book Your ASURE Stay Online">Book Now</a>
					<img class="loyaltyCard" src="http://www.asurestay.com/~images/template/common/ASURE_loyaltycard-01.png" title="ASURE Accommodation Loyalty Card" />
				</div>
				<!-- end -->
			</div>
			<div class="columns four">
				<div class="footerApp">
					<h4>Get the ASURE Mobile App</h4>
					<a class="btn" href="https://play.google.com/store/apps/details?id=com.guestfolder.asure" title="ASURE Android App from Google Play" target="_blank">
						<img src="images/btn_google.jpg" alt="Google Play" />
					</a>
					<a class="btn" href="https://itunes.apple.com/us/app/asure-accommodation-group/id1150322731?ls=1&mt=8" title="ASURE iOS App from the Apple App Store" target="_blank">
						<img src="images/btn_apple.jpg" alt="Apple App Store" />
					</a>
				</div>
			</div>
	</div>
	<div class="row">
		<!-- keep the card image up to date with ASUREstay.com -->
		<div class="footerCards">
			<img alt="Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards" src="http://www.asurestay.com/~images/template/common/ASURE_cards06.jpg" />
			<p>ASURE Accommodation Group Accepts All Major Credit Cards and: Farmlands, Q Card, RuralCo, Fonterra Farm Source, Farmers Card, Super Gold, and China Union Pay Cards.</p>
		</div>
		<!-- end -->
		<div class="footerLinks">
			ASURE Accommodation Group <span class="dash">|</span>
			<a href="http://www.ASUREstay.com" title="ASURE Accommodation Group NZ" target="_blank">www.ASUREstay.com</a> <span class="dash">|</span>
			Your Comfort is ASUREd 
		</div>
	</div>
</div>

<div id="footerCopy">
	&copy; %YEAR% ASURE Accommodation Group - 
	<a href="/sitemap.html" title="Website Site Map">Sitemap</a> -					
	<a href="http://www.welman.co.nz/webrooms-login.asp" title="Admin Login">Admin Login</a> - 
	%CREDITLINK%
</div>

</body>