
    <footer class="footer text-center bg-dark">
      <div class="container">
        <div class="row">
        
          <div class="col-md-4 text-lg-left text-md-center">
						<h3>Quick Links</h3>
						<a class="text-white" href="%SITE_CUSTOM_CONTENT_3%holidays/">Holidays</a><br><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%health/">Health</a><br><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%forms-and-documentation/">Forms and Documentation</a><br><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%terms-and-conditions/"><span>Terms and Conditions</span></a><br><a class="text-white" href="%SITE_CUSTOM_CONTENT_3%privacy-policy/"><span>Privacy Policy</span></a></div><div class="col-md-4 text-center">
						<h3>Join Us</h3>
						<a class="text-white" href="%SITE_CUSTOM_CONTENT_3%join-membership/"><span>Become a member</span></a></div><div class="col-md-4 text-lg-right text-md-center">
						<h3>Contact Us</h3>
						<span>Email: <a class="text-white" href="mailto:info@nzrwelfare.co.nz">info@nzrwelfare.co.nz</a></span><br><span>Free Phone: <a class="text-white" href="tel:0800806444">0800 806 444</a></span><br><span>A New Zealand Registered Company</span></div>

        <div class="col-12 border-top mt-3 pt-3">
            <ul class="list-inline mb-0 mt-2">            
              <li class="list-inline-item">
                <a class="btn btn-outline-light btn-social text-center rounded-circle" href="https://www.facebook.com/nzrwelfare" target="_blank">
                  <i class="fab fa-fw fa-facebook-f"></i>
                </a>
              </li>
            </ul>
          </div>
      </div>
    </footer>


    <div class="copyright py-4 text-center text-white">
      <div class="container">
        <small>Copyright &copy; %YEAR% - <a href="%SITE_CUSTOM_CONTENT_3%admin/" class="text-light">Admin login</a> - <a class="text-light" href="https://www.guesttraction.com/" target="_blank">Website by GuestTraction</a></small>
      </div>
    </div>


<!-- js -->	
<script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js"></script>
<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
<script src="js/lightbox.min.js"></script>
<script src="js/jquery.dotdotdot.min.js"></script>
<script src="js/custom.js"></script>

<!-- css -->	
<link href="css/lightbox.css" rel="stylesheet" />
<link rel="stylesheet" href="https://code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">

<!-- scripts -->
<script type="text/javascript">
		$(document).ready(function() {
			$(".ellipsis").dotdotdot({
				ellipsis	: '... ',
			});
		});
</script>