.headerBackground { height:330px; background:url(images/background_header01.jpg) center center no-repeat; background-size:cover; margin-top:140px; }
.reviewTitle { margin:65px auto 20px; }
.reviewTitle a { color:#fff; font-size:26px; font-weight:300; font-style:italic; text-align:center; text-shadow:1px 1px 1px rgba(0,0,0,0.3); }
.headerBook { display:none; }
.bookBox { text-align:center; }
.webrooms-datepicker { display:inline-block; margin:auto; text-align:left; }
.bookBox .datepicker-label, 
.bookBox .datepicker-input,
.bookBox .datepicker-button { line-height:55px; height:55px; font-size:18px; }	
.bookBox .datepicker-label { width:350px; text-indent:40px; height:53px; }
.bookBox .datepicker-label:before { line-height:55px; height:55px; left:15px; }
.bookBox .datepicker-input { left:120px; width:200px; }

#homeBoxes { margin-top:30px; }
#homeBoxes .six { position:relative; background:#f7f7f7; }
#homeBoxes h2.pageTitle { background:#333; text-align:center; line-height:50px; }
#homeBoxes h2.pageTitle a { color:#fff; font-weight:400; }
.slideControls { height:270px; position:absolute; width:100%; z-index:999; }
.propPrev, .propNext { position:absolute; top:0; left:0; z-index:1000; border:none; width:50px; line-height:50px; background:none; color:#fff; opacity:0.3; outline:none; }
.propPrev:hover, .propNext:hover { cursor:pointer; opacity:0.9; }
.propNext { right:0; left:initial; }
.slide0 { margin-top:50px; }

.rwrRoomtype { padding:0; margin:0; border:none; min-height:0; background:#f7f7f7; padding:0 30px; position:relative; padding-top:220px; min-width:399px; }
.rwrRoomtype .desc-images { position:static; width:auto; position:absolute; top:0; left:0; right:0; height:220px; }
.rwrRoomtype h2, 
.rwrRoomtype .fromCap, 
.rwrRoomtype .popup-desc { width:auto; max-width:none; }
.rwrRoomtype .desc-avail,
.rwrRoomtype .desc-features-outer,
.rwrRoomtype .desc-images a { display:none; }
.rwrRoomtype .desc-images a.first { display:block; }
.rwrRoomtype h2 { padding-top:30px; }
.rwrRoomtype .desc-description-outer { height:60px; max-height:60px; overflow:hidden; }

.event-teasers ul.event-list-inner { margin:0; padding:0; }
.event-teasers li.event-inner { margin:0; padding:0; background:#f7f7f7; padding:0 30px; position:relative; padding-top:220px; }
.event-teasers .event-image { position:absolute; top:0; left:0; right:0; height:220px; background-size:cover; background-position:center center; }
.event-teasers .event-name { font-weight:700; font-size:120%; padding-top:30px; }
.event-teasers .event-teaser { margin:10px 0; max-height:60px; }
.event-teasers .event-venue { color:#999; }
.event-teasers a.event-link { display:none; }

.homeboxLink { padding:30px; padding-top:0; font-weight:600; }

@media only screen and (max-width: 960px) 
{
.headerBackground { margin-top:50px; height:350px; }
.reviewTitle { margin:50px 1.5em; }
.reviewTitle a { font-size:125%; }
#homeBoxes { margin:0; }
#homeBoxes .six { margin-bottom:1.5em; }
.slide0 { margin-top:1.5em; }
.bookBox { margin:2em auto; right:0; max-width:85%; width:auto; }
.webrooms-datepicker { width:100%; }
.bookBox .datepicker-label,
.bookBox .datepicker-input,
.bookBox .datepicker-button { width:100%; margin:0 auto; left:initial; top:initial; right:initial; position:static; font-size:100%; display:block; height:auto; line-height:100%; text-align:center; }
.bookBox .datepicker-label,
.bookBox .datepicker-label:before { display:none; }
.bookBox .datepicker-input { background:#fff; border-radius:3px; box-shadow:0 1px 3px rgba(0,0,0,0.2); margin-bottom:0.5em; padding:0.5em 0; }
.bookBox .datepicker-button { padding:0.5em 0; color:#fff; }
}










