<script src="js/js.js"></script>
<link href="%GLOBAL_ROOT%websites/common/css/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
<link href="%GLOBAL_ROOT%websites/common/css/css_grid.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_articles_16v2.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_articles-home_16v1.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_buttons_16v2.css" rel="stylesheet" />	 <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_common_16v2.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_datepicker_16v2.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_forms_16v2.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_nav-responsive.css" rel="stylesheet" />
<link href="%GLOBAL_ROOT%websites/common/css/css_roomtypes_16v2.css" rel="stylesheet" /> <!-- new -->
<link href="%GLOBAL_ROOT%websites/common/css/css_social_16v1.css" rel="stylesheet" />
<script type="text/javascript" charset="utf-8" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&amp;sensor=false"></script>
%WEBROOMS_JS_INCLUDE%

<style>
	%SITE_CUSTOM_CSS%
	%PAGE_CUSTOM_CSS%
</style>

%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,400italic,600,700,800' rel='stylesheet' type='text/css'>
<link href="https://fonts.googleapis.com/css?family=Quattrocento" rel="stylesheet">
%SITE_CUSTOM_CONTENT_1%
</head>