		
		<script src="js/jquery.cycle2.min.js"></script>
		<script src="js/jquery.cycle2.carousel.min.js"></script>
		<script src="js/jquery.cycle2.swipe.min.js"></script>		
		<script src="js/jquery.dotdotdot.min.js"></script>
		<script src="js/lightbox.min.js"></script>		
		<link href="css/lightbox.css" rel="stylesheet" />		
		
		<script src="js/js.js"></script>
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&sensor=false"></script>		
		<link href="https://fonts.googleapis.com/css?family=Open+Sans:400italic,300,400,600,700,800" rel="stylesheet" type="text/css"/>
		<link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
		
		<script src="js/responsive-nav.js"></script>
		<script src="js/jquery-scrolltofixed-min.js"></script>
		<script>
				$(document).ready(function() {
				  $('#homeListings #sid-5867 thead').scrollToFixed();
				});
		</script>

		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		</style>
		
		%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
		
	</head>
	<body class="bodyStyle">
		
		
		
						