		
		<script src="%GLOBAL_ROOT%js/jquery.cycle2.min.js"></script>
		<script src="js/jquery.cycle2.carousel.min.js"></script>
		<script src="js/jquery.cycle2.swipe.min.js"></script>
		<script src="js/responsive-nav.js"></script>
		<script src="js/lightbox.min.js"></script>
		<script src="js/jquery.dotdotdot.min.js"></script>
		<script src="js/js.js"></script>
		<link href="css/lightbox.css" rel="stylesheet" />
		<link href="css/responsive_960grid.css" rel="stylesheet" />
		<link href="css/host.css" rel="stylesheet" />
		
		<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB9yaIoZlsvDLL66hCTO6BFA82tQMSeObc&sensor=false"></script>		
		
		<script src="js/responsive-nav.js"></script>
		<script src="js/jquery-scrolltofixed-min.js"></script>
		<script>
				$(document).ready(function() {
				  $('#homeListings #sid-5867 thead').scrollToFixed();
				});
		</script>

		<style>
		%SITE_CUSTOM_CSS%
		%PAGE_CUSTOM_CSS%
		</style>
		
		%GOOGLE_ANALYTICS_TRACKER_UNIVERSAL%
		
		<!--[if lte IE 8]>
			<link rel="stylesheet" type="text/css" href="css/ie.css" />
		<![endif]-->
	
<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,900,400italic' rel='stylesheet' type='text/css' />
<link href='http://fonts.googleapis.com/css?family=Roboto+Slab:300,700,400' rel='stylesheet' type='text/css' />
%SITE_CUSTOM_CONTENT_1%

<style>
			html, body {
				margin:0;
				padding:0;
				font-family:'Source Sans Pro', 'sans-serif';
				font-size:16px;
				color:#333;
				background:#f5f5f5;
				font-weight:400;
			}
</style>
		
	</head>
	<body class="bodyStyle">
