		
						
<div class="footerCopy">

<div class="footerLogos">
<img src="images/logo_accommnz.jpg" alt="Accommodation NZ" title="Accommodation NZ Members" />
</div>


		&copy; %YEAR% TaranakiMotels.co.nz
			<span class="footerSpacer">|</span>
		<a href="sitemap.html">Site Map</a> 
			<span class="footerSpacer">|</span>
		<a href="http://www.welman.co.nz/webrooms-login.asp" rel="nofollow">Admin Login</a>
			<span class="footerSpacer">|</span>
		%CREDITLINK%
</div>

<script>
  var nav = responsiveNav(".nav-collapse");
</script>

