<div class="footerBlock">
	<div class="row">
		<div class="footerLAM">
			<a href="index.html" title="Look After Me - Accommodation Group New Zealand">
				<img src="images/LAM-logo.png" alt="Look After Me - New Zealand's Accommodation" />
			</a>
		</div>

		<div class="footerCopy">
		
			&copy; %YEAR% Look After Me Network New Zealand - 
			<a href="sitemap.html" title="Sitemap">Sitemap</a> - 
			<a href="terms.html">Terms and conditions</a> - 
			%CREDITLINK%
		</div>
	</div>
</div>

<script src="js/jquery-scrolltofixed-min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function() {
        $('.headerBar').scrollToFixed();
    });
    
</script>